version: '3'

services:
  db:
    image: mysql:8.2.0
    command: --lower_case_table_names=1
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: poc
    volumes:
      - ./.docker/mysql8:/var/lib/mysql
      - ./db-script.sql:/app/db-script.sql
      - ./docker-entrypoint-initdb.sh:/docker-entrypoint-initdb.d/docker-entrypoint-initdb.sh
